stages:
  - test
  - deploy

Unit Tests:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - flake8 .

Deploy DEV:
  stage: deploy
  image: google/cloud-sdk:alpine
  script:
    - ./ingestion/publish_tweet_requests/deploy.sh
