stages:
  - test
  - deploy dev

Unit Tests:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt
    - flake8 .

Deploy DEV:
  stage: deploy dev
  image: google/cloud-sdk:alpine
  variables:
    GOOGLE_CREDENTIALS: $GOOGLE_CREDENTIALS_DEV
    GOOGLE_PROJECT_ID: $GOOGLE_PROJECT_ID_DEV
  script:
    - ./ingestion/publish_tweet_requests/deploy.sh
