stages:
  - deploy dev
  - integration test

Deploy DEV (python):
  stage: deploy dev
  image: python:3.8
  variables:
    GOOGLE_PROJECT_ID: $GOOGLE_PROJECT_ID_DEV
    GOOGLE_REGION: $GOOGLE_REGION_DEV
    GOOGLE_SERVICE_ACCOUNT_EMAIL: $GOOGLE_SERVICE_ACCOUNT_EMAIL_DEV
  script:
    - pip install virtualenv
    - echo $GOOGLE_CREDENTIALS > /tmp/$CI_PIPELINE_ID.json
    - type /tmp/$CI_PIPELINE_ID.json
    - ./dataflow/compute_sentiment_pipeline/deploy.sh

Integration Tests:
  stage: integration test
  image: python:3.8
  variables:
    GOOGLE_CREDENTIALS: $GOOGLE_CREDENTIALS_DEV
    GOOGLE_PROJECT_ID: $GOOGLE_PROJECT_ID_DEV
    GOOGLE_REGION: $GOOGLE_REGION_DEV
    GOOGLE_SERVICE_ACCOUNT_EMAIL: $GOOGLE_SERVICE_ACCOUNT_EMAIL_DEV
  script:
    - pip install -r requirements.txt
    - pytest -v -m "integration" ingestion
    - pytest -v -m "integration" dataflow
