stages:
  - test
  - deploy
  - integration

Unit Tests:
  stage: test
  image: python:3.8
  variables:
    GOOGLE_CREDENTIALS: $GOOGLE_CREDENTIALS_DEV
    GOOGLE_PROJECT_ID: $GOOGLE_PROJECT_ID_DEV
  script:
    - pip install -r requirements.txt
    - flake8 .
    - pytest -v -m "not integration"

Deploy DEV:
  stage: deploy
  image: google/cloud-sdk:alpine
  variables:
    GOOGLE_CREDENTIALS: $GOOGLE_CREDENTIALS_DEV
    GOOGLE_PROJECT_ID: $GOOGLE_PROJECT_ID_DEV
  script:
    - ./ingestion/publish_tweet_requests/deploy.sh
    - ./ingestion/request_tweets/deploy.sh

Integration Tests:
  stage: integration
  image: python:3.8
  variables:
    GOOGLE_CREDENTIALS: $GOOGLE_CREDENTIALS_DEV
    GOOGLE_PROJECT_ID: $GOOGLE_PROJECT_ID_DEV
  script:
    - pip install -r requirements.txt
    - pytest -v -m "integration"
